<?php declare(strict_types=1);

/*
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * Module installation parameters
 *
 * This script conforms to the Xoops standard for xoops_version.php
 *
 * @copyright (c) 2004, Ashley Kitson
 * @copyright     XOOPS Project https://xoops.org/
 * @license       GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @author        Ashley Kitson http://akitson.bbcb.co.uk
 * @author        XOOPS Development Team
 * @package       EUVAT
 * @subpackage    Installation
 * @access        private
 * @version       1
 */

$moduleDirName      = basename(__DIR__);
$moduleDirNameUpper = mb_strtoupper($moduleDirName);

$modversion['version']             = 2.01;
$modversion['module_status']       = 'Beta 1';
$modversion['release_date']        = '2020/08/30';
$modversion['name']                = _MI_XBSVAT_NAME;
$modversion['description']         = _MI_XBSVAT_DESC;
$modversion['credits']             = 'Ashley Kitson<br>( http://xoobs.net/ ), Benjamin Boigienman, France';
$modversion['author']              = 'Ashley Kitson';
$modversion['license']             = 'GPL see LICENSE';
$modversion['official']            = 0;
$modversion['dirname']             = $moduleDirName;
$modversion['modicons16']          = 'assets/images/icons/16';
$modversion['modicons32']          = 'assets/images/icons/32';
$modversion['image']               = 'assets/images/logoModule.png';
$modversion['onUninstall']         = 'install_funcs.php';
$modversion['onInstall']           = 'install_funcs.php';
$modversion['onUpdate']            = 'install_funcs.php';
$modversion['module_website_url']  = 'https://xoops.org';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '7.1';
$modversion['min_xoops']           = '2.5.10';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = ['mysql' => '5.5'];
$modversion['adminindex']          = 'admin/index.php';
$modversion['adminmenu']           = 'admin/menu.php';

// ------------------- Help files ------------------- //
//$modversion['help'] = "euvathelp.html";
$modversion['help']        = 'page=help';
$modversion['helpsection'] = [
    ['name' => _MI_XBSVAT_OVERVIEW, 'link' => 'page=help'],
    ['name' => _MI_XBSVAT_DISCLAIMER, 'link' => 'page=disclaimer'],
    ['name' => _MI_XBSVAT_LICENSE, 'link' => 'page=license'],
    ['name' => _MI_XBSVAT_SUPPORT, 'link' => 'page=support'],
];

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
//No tables created for EU VAT.  Code data is put into CDM tables
// by install sql script
//$modversion['tables'][0] = "";

// Main Menu
$modversion['hasMain'] = 0;

// Templates
// No main templates
//$modversion['templates'][1]['file'] = '';
//$modversion['templates'][1]['description'] = '';

// Admin menu things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;

//Search things
$modversion['hasSearch'] = 0;

//User comments things
$modversion['hasComments'] = 0;

//Module notification things
$modversion['hasNotification'] = 0;

// Blocks
$modversion['blocks'][1]['file']        = 'euvat_block_lookup.php';
$modversion['blocks'][1]['name']        = _MI_XBSVAT_BLOCK_CODELOOKUPNAME;
$modversion['blocks'][1]['description'] = _MI_XBSVAT_BLOCK_CODELOOKUPDESC;
$modversion['blocks'][1]['show_func']   = 'b_euvat_lookup_show';
$modversion['blocks'][1]['edit_func']   = 'b_euvat_lookup_edit';
$modversion['blocks'][1]['options']     = 'GB'; //Default EU Country code
$modversion['blocks'][1]['template']    = 'euvat_block_lookup.tpl';
