INSERT INTO cdm_meta (cd_set, cd_type, cd_len, val_type, val_len, cd_desc) VALUES ('EUVAT', 'CHAR', 2, 'CHAR', 2, 'EU VAT Country Codes and Number Validations');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'AT', 'AT', 'Austria', 'U[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'BE', 'BE', 'Belgium', '0?[0-9]{*}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'CZ', 'CZ', 'Czech Republic', '[0-9]{8,10}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'DE', 'DE', 'Germany', '[0-9]{9}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'CY', 'CY', 'Cyprus', '[0-9]{8}[A-Z]');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'DK', 'DK', 'Denmark', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'EE', 'EE', 'Estonia', '[0-9]{9}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'EL', 'GR', 'Greece', '[0-9]{9}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'ES', 'ES', 'Spain', '[0-9A-Z][0-9]{7}[0-9A-Z]');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'FI', 'FI', 'Finland', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'FR', 'FR', 'France', '[0-9A-Z]{2}[0-9]{9}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'GB', 'GB', 'United Kingdom', '([0-9]{9}|[0-9]{12})~(GD|HA)[0-9]{3}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'HU', 'HU', 'Hungary', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'IE', 'IE', 'Ireland', '[0-9][A-Z0-9\\+\\*][0-9]{5}[A-Z]');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'IT', 'IT', 'Italy', '[0-9]{11}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'LT', 'LT', 'Lithuania', '([0-9]{9}|[0-9]{12})');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'LU', 'LU', 'Luxembourg', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'LV', 'LV', 'Latvia', '[0-9]{11}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'MT', 'MT', 'Malta', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'NL', 'NL', 'Netherlands', '[0-9]{9}B[0-9]{2}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'PL', 'PL', 'Poland', '[0-9]{10}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'PT', 'PT', 'Portugal', '[0-9]{9}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'SE', 'SE', 'Sweeden', '[0-9]{12}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'SI', 'SI', 'Slovenia', '[0-9]{8}');
INSERT INTO cdm_code (cd_set, cd_lang, cd, cd_value, cd_desc, cd_param) VALUES ('EUVAT', 'EN', 'SK', 'SK', 'Slovakia', '[0-9]{10}');
